apiVersion: v1
kind: Service
metadata:
  name: solarsystem-service
  namespace: prod-ns
spec:
  selector:
    app: solarsystem
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
