---
- hosts: k3s
  become: yes
  tasks:

    - name: Transfer Kubernetes YAML templates from the runner to EC2
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0644'
      loop:
        - { src: "deployment.yaml", dest: "/home/ubuntu/deployment.yaml" }
        - { src: "service.yaml", dest: "/home/ubuntu/service.yaml" }
        - { src: "namespace.yaml", dest: "/home/ubuntu/namespace.yaml" }
#        - { src: "./kubernetes/deployment.yaml", dest: "/home/ubuntu/deployment.yaml" }
        # Add other YAML files as needed

    - name: Apply Kubernetes service YAML
      command: kubectl apply -f /home/ubuntu/namespace.yaml

    - name: Apply Kubernetes deployment YAML
      command: kubectl apply -f /home/ubuntu/deployment.yaml

    - name: Apply Kubernetes service YAML
      command: kubectl apply -f /home/ubuntu/service.yaml

#    - name: deploy the dockerized app to production environment
#      shell: |
#        kubectl apply -f ./kubernetes/namespace.yaml
#        kubectl apply -f ./kubernetes/deployment.yaml
#        kubectl apply -f ./kubernetes/service.yaml

#    - name: check all kubernetes resources in the prod-ns namespace
#      shell: kubectl get all -n pord-ns
