---
- hosts: k3s
  become: yes
  gather_facts: true
  tasks:
    - name: Ensure K3s is running
      shell: |
        systemctl status k3s

    - name: Retrieve K3s kubeconfig
      shell: cat /etc/rancher/k3s/k3s.yaml
      register: k3s_kubeconfig

      
    - name: Create .kube directory
      file:
        path: ~/.kube
        state: directory
        mode: '0755'

    - name: Save K3s kubeconfig for kubectl access
      local_action:
        module: copy
        content: "{{ k3s_kubeconfig.stdout }}"
        dest: ~/.kube/config
        mode: '0644'
