name: solar system workflow
on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    #MONGO_USERNAME: 'superuser'
    #MONGO_PASSWORD: 'SuperPassword'

jobs:
    unit-testing:
        name: unit testing
        strategy:
            matrix:
                nodejs_version: [18,19,20]
                os: [ubuntu-latest,macos-latest]
                exclude:
                    - nodejs_version: 18
                      os: macos-latest
        #runs-on: ubuntu-latest
        runs-on: ${{ matrix.os }}
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: ${{ matrix.nodejs_version }}
            #- name: setup Node Js Version 18
              uses: actions/setup-node@v3
              with:
                #node-version: 18
                node-version: ${{ matrix.nodejs_version }}

            - name: install depend.
              run: npm install

            - name: unit testing
              run: npm test

            - name: Archive test result
              uses: actions/upload-artifact@v3
              with:
                name: mocha-test-result
                path: test-results.xml